### ISSUE TITLE
userManager.signinCallback() is called for a logged in user causing uncaught exception

### ISSUE THREAD

**Issue by pigletto** [bjerkio/oidc-react#307] opened 2020-10-23 13:15 UTC
When the user is already logged in but the URL contains the 'code' parameter, oidc-react raises an "No matching state found in storage" exception.

This is because the userManager.signinCallback is always called if there is a 'code' in the URL even though it shouldn't if the user is already logged in (as the state seems to be removed at this time).

The code is at https://github.com/bjerkio/oidc-react/blob/master/src/AuthContext.tsx#L87

I've seen this in my application with the most recent oidc-react and using Google Chrome but it is easy to reproduce using the online demo for oidc-react:

1. Visit the demo application: https://cobraz.github.io/example-oidc-react/
2. Log in
3. When the popup appears saying you're logged in then do not close it(!) but copy the URL from the address bar (should be something like: https://cobraz.github.io/example-oidc-react/#state=3718c8c9ff504d89b98d06108753d414&id_token=xyz.xyz&authuser=0&prompt=none)
4. Open the new browser tab and paste the URL copied in 3.
5. Check the console for errors

There should be an exception shown:
Uncaught (in promise) Error: No matching state found in storage

**Comment by cobraz** [comment] 2020-10-24 22:15
Thank for you submitting an issue!

This is actually intended behaviour by the underlying package. That being said, I'd like to see how we can improve the developer experience in this field, so I've created a new issue about this to cover that. #313 

The "current fix": Many users add a step in `onSignIn` where the URL is cleaned up (such as in [cobraz.github.io/example-oidc-react](https://github.com/cobraz/example-oidc-react))

Let me know if you have any further questions, I'll close this for now :)

**Closed by cobraz** 2020-10-24 22:15 UTC

**Comment by pigletto** [comment] 2020-10-26 07:40
@cobraz it seems to me that it is react-oidc that calls userManager.signinCallback when it shouldn't (as the user is already logged in) causing an exception. Because of that I don't think it is an intended behaviour of the underlying package. It should be enough to check if user is already logged in in the react-oidc to avoid the exception. Please have a look at a commit referenced above. It seems to me it should resolve the issue.
