### ISSUE TITLE
CORS 

### ISSUE THREAD

**Issue by SimonX2h** [bjerkio/oidc-react#1004] opened 2023-05-18 14:33 UTC
Uncaught (in promise) Error: Response is undefined inside a success
    at OidcServiceWorker.js:1:6495
(anonymous) @ OidcServiceWorker.js:1
oidc-client-ts.js:532     POST https://localhost:44350/connect/token net::ERR_FAILED
fetchWithTimeout @ oidc-client-ts.js:532
postForm @ oidc-client-ts.js:614
exchangeCode @ oidc-client-ts.js:972
await in exchangeCode (async)
_processCode @ oidc-client-ts.js:1246
validateSigninResponse @ oidc-client-ts.js:1110
processSigninResponse @ oidc-client-ts.js:1645
await in processSigninResponse (async)
_signinEnd @ oidc-client-ts.js:2746
signinRedirectCallback @ oidc-client-ts.js:2507
signinCallback @ oidc-client-ts.js:2639
await in signinCallback (async)
eval @ AuthContext.js:180
step @ AuthContext.js:67
eval @ AuthContext.js:48
fulfilled @ AuthContext.js:39
Promise.then (async)
step @ AuthContext.js:41
eval @ AuthContext.js:42
__awaiter @ AuthContext.js:38
eval @ AuthContext.js:171
eval @ AuthContext.js:204
commitHookEffectListMount @ react-dom.development.js:23150
commitPassiveMountOnFiber @ react-dom.development.js:24926
commitPassiveMountEffects_complete @ react-dom.development.js:24891
commitPassiveMountEffects_begin @ react-dom.development.js:24878
commitPassiveMountEffects @ react-dom.development.js:24866
flushPassiveEffectsImpl @ react-dom.development.js:27039
flushPassiveEffects @ react-dom.development.js:26984
commitRootImpl @ react-dom.development.js:26935
commitRoot @ react-dom.development.js:26682
performSyncWorkOnRoot @ react-dom.development.js:26117
flushSyncCallbacks @ react-dom.development.js:12042
eval @ react-dom.development.js:25651
oidc-client-ts.js:532     Uncaught (in promise) TypeError: Failed to fetch
    at JsonService.fetchWithTimeout (oidc-client-ts.js:532:1)
    at JsonService.postForm (oidc-client-ts.js:614:1)
    at TokenClient.exchangeCode (oidc-client-ts.js:972:1)
    at async ResponseValidator._processCode (oidc-client-ts.js:1246:1)
    at async ResponseValidator.validateSigninResponse (oidc-client-ts.js:1110:1)
    at async OidcClient.processSigninResponse (oidc-client-ts.js:1645:1)
    at async UserManager._signinEnd (oidc-client-ts.js:2746:1)
    at async UserManager.signinRedirectCallback (oidc-client-ts.js:2507:

**Comment by simenandre** [comment] 2023-05-18 17:48
Can you please share some more context?

**Comment by simenandre** [comment] 2023-06-12 20:51
This is likely caused by the server, not this package.

Let me know if there is anything else we can help with! I'm closing this for now :)

**Closed by simenandre** 2023-06-12 20:51 UTC
Labels: awaiting-feedback

**Comment by emleonid** [comment] 2024-03-01 12:48
> This is likely caused by the server, not this package.
> 
> Let me know if there is anything else we can help with! I'm closing this for now :)

@simenandre

**Please, help me understand.**

- OpenId server on identity.example.com
- React App on example.com
- OpenId server has example.com in allowed origins.
- And for the Safari browsers (mobile and desktop), from unpredicted scenarios, it throws a CORS error while trying to fetch https://identity.example.com/.well-known/openid-configuration.
- And we see **TypeError Load failed** error in our logs.

![Screenshot_1](https://github.com/bjerkio/oidc-react/assets/11710490/e92afde9-d434-406c-8424-c878ad4e9b6a)

Where is the identity server problem when CORS works perfectly for all browsers except Safari?
